### ISSUE TITLE
BinData logged as hex, but eJSON requires base64

### ISSUE THREAD

**Issue by devkev** [mongodb-js/mongodb-log2ejson#2]
In the strict mode extended JSON format, the string specified in the `"$binary"` field is a base64 encoded representation of the binary data.  However, the "BinData" in logfiles has hex encoded data.

http://docs.mongodb.org/manual/reference/mongodb-extended-json/#data_binary

This means that the simple regexp approach that this code currently uses needs to be extended, and the hex data will need to be parsed and base64 encoded.

**Comment by imlucas** [comment]
@rueckstiess mind taking a peak at this when you get a chance?

**Comment by rueckstiess** [comment]
on it, but as part of merging this whole thing into [mongodb-extended-json](https://github.com/mongodb-js/extended-json/issues/3). See you over there.
